### ISSUE TITLE
Panel sections state is not persisted across selections

### ISSUE THREAD

**Issue by andreasgeier** [bpmn-io/properties-panel#102]
__Describe the Bug__

If a user expands or closes a specific section of the property panel, it does not persist in its state during the user session.
(Bug originally reported by @falko)

__Steps to Reproduce__

1. Open Modeler with new properties panel
2. Create a task and a gateway
3. Create an input on the task, create a condition on the sequence flow to the gateway
4. Switch selection between the symbols
5. Result: expanded sections like Input and Conditions are closed and must be opened each time a new selection is made

__Expected Behavior__

Persist the state of each section. If a section such as "Condition" has been opened once, it must stay open during the entire user session. It doesn't matter if other symbols without a Condition section have been selected in the meantime, if a symbol with a Condition section is selected again, the section must be opened.

This expected behavior is valid for all sections of the properties panel and all states (expanded, collapsed).

Consider, that list sections without content cannot be opened. So, if a user creates inputs on one symbol and switches to another symbol without existing inputs, the section on the latter is closed (because empty) but remains open on the former (and all other symbols with existing symbols).

__Environment__

 * Version: 4.10.0
 * Operating System: Mac OS 11.6.0 
 * Plugins: BPMN Linter, Cloud Connect
 * Execution Platform: BPMN - Camunda Cloud

**Comment by pinussilvestrus** [comment]
Thanks 👍 I am closing this issue in favor of https://github.com/bpmn-io/properties-panel/issues/98.
