### ISSUE TITLE
Builds failing on Windows due to pathing issues

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/properties-panel#127]
__Describe the Bug__

On Windows specifically, the package cannot be built at all, as multiple modules relating to preact cannot be resolved.

```
ERROR in ./preact/hooks/dist/hooks.module.js 1:0-37
Module not found: Error: Can't resolve '....' in 'C:\dev\bpmn-io\properties-panel\properties-panel\preact\hooks\dist'
 @ ./src/PropertiesPanel.js 1:0-54 84:30-38 85:2-11
 @ ./test/spec/PropertiesPanel.spec.js 5:0-50 258:21-36
 @ ./test/ sync .spec\.js$ ./spec/PropertiesPanel.spec.js test/spec/PropertiesPanel.spec.js
 @ ./test/testBundle.js 1:17-57
 ```

__Steps to Reproduce__

1. Clone the repo on a Windows machine
2. Execute `npm install`
3. Execute `npm run dev`

__Expected Behavior__

We expect the build to complete without errors.

__Environment__

- Host: Node v14
- OS: Window 10
- Library version: 0.10.0

**Comment by marstamm** [comment]
Hypothesis: in the rewire step, Windows paths are not properly escaped. Cf. https://github.com/bpmn-io/properties-panel/blob/6ceac4f11124fb2a82627f17f0245c496a1c862c/rollup.config.js#L55-L74

I can't test it on windows right now

**Comment by marstamm** [comment]
Let's also consider adding Windows + Mac as additional OS on CI
https://github.com/bpmn-io/properties-panel/blob/main/.github/workflows/CI.yml
