### ISSUE TITLE
Bundling `preact` causes duplicate versions to be packaged in user bundles

### ISSUE THREAD

**Issue by boris-petrov** [bpmn-io/properties-panel#149]
__Describe the Bug__

My build started failing when I started using `@bpmn-io/properties-panel`. The error is:

```
ERROR in preact
  Multiple versions of preact found:
    10.5.13 ./~/@bpmn-io/properties-panel/preact from ./~/bpmn-js-properties-panel/dist/index.esm.js
    10.7.1 ./~/preact from ./~/@fullcalendar/core/vdom.js
```

That is, because `@bpmn-io/properties-panel` bundles "manually" `preact` (not using `package.json` as a normal `dependency`), a Webpack plugin that I use (`@cerner/duplicate-package-checker-webpack-plugin`) for checking for duplicate packages complains about `preact` because it is now bundled twice.

Why was this change done? This is not the standard way of dealing with dependencies - and cause issues like mine.

__Steps to Reproduce__

Please see above for a description.

__Expected Behavior__

`preact` to be depended-on "normally" - via `dependencies` in `package.json`.

__Environment__

- Host (Browser/Node version), if applicable: Browser
- OS: Linux
- Library version: 0.13.2

**Comment by barmac** [comment]
Hi,

thanks for creating this issue. We've decided to include `preact` inside the package to:

1) Resolve the issues pointed out in https://github.com/camunda/camunda-bpmn-js/issues/113
2) Not force user to maintain a properties-panel-specific version of preact (which would be the case if preact was a peer dependency.

We are however open to discussion. To resolve your issue for now, I'd suggest making sure that the duplicate checker ignores the preact package vendored in `@bpmn-io/properties-panel`

**Comment by boris-petrov** [comment]
Thanks for the information!

I believe that ignoring the warning from the duplicate checker is not a very good solution because in that case my bundle **will** contain two copies of preact. Which is not ideal. I actually resolved it by adding `preact: __dirname + '/node_modules/@bpmn-io/properties-panel/preact'` in `resolve.alias` in my Webpack config which I believe is a better solution (although the preact version bundled in `@bpmn-io/properties-panel` is pretty old one but I guess it's better to use it rather than a newer one because `@bpmn-io/properties-panel` might not work with it I suppose?).

**Comment by nikku** [comment]
>  (although the preact version bundled in @bpmn-io/properties-panel is a pretty old one but I guess it's better to use it rather than a newer one because @bpmn-io/properties-panel might not work with it?).

@boris-petrov That is exactly the point. We bundle it, because it is part of our infrastructure, not something you ought to use / rely upon. If there is a way to exclude it from your duplicate checker, please investigate that.

If you rely on our (internally bundled) Preact you're depending on something that can change any time, without prior warning. Don't do that.

**Comment by boris-petrov** [comment]
@nikku - I don't "rely" on the bundled `preact` but I point all other packages to depend on that version of `preact`. Otherwise I would get `preact` twice in my bundle which is not something I want. Do you see what I mean? I don't rely on any specific features of this `preact` version, I just have to tell `webpack` to use only ONE version (which I've chosen to be the one from `bpmn.js`).

**Comment by nikku** [comment]
@boris-petrov I can relate to you're case of "not wanting a library bundled twice".

Please consider "Preact being used in our tools" an implementation detail though. It could be replaced with inferno, snabdom, or plain JS any time. That is the whole point of us bundling it; you should not be aware, and you should not care. We shall work towards making that clear @barmac; let us chat about that.

**Comment by boris-petrov** [comment]
Fair enough! When you've put it that way, it makes sense. Thanks for taking the time to explain!
