### ISSUE TITLE
Implement optgroup in SelectEntry

### ISSUE THREAD

**Issue by Ichigo85** [bpmn-io/properties-panel#169]
__Is your feature request related to a problem? Please describe__

I am developing (and/or rewriting) my own properties panel module, specifically for Camunda Modeler but not necessary related to it. While developing a select box I noted that's not possible to define a select box with the optgroup tag and it would be a bit hard to develop it on my own.

__Describe the solution you'd like__

I would like to add a prop to the SelectEntry component to allow optgroups while adding options

__Describe alternatives you've considered__

Another alternative was to create a "parent" select box for my groups, but since there is no model property for them because it's a way to set different delegateExpression values, a single select with optgroups would do the trick.

__Additional context__

Here is a screenshot of my selectbox in Camunda Modeler 4.
![image](https://user-images.githubusercontent.com/27808087/179940077-641d264f-5f2a-40fa-b221-4ee45758a8eb.png)

**Comment by pinussilvestrus** [comment]
Makes sense, thanks for opening 👍
