### ISSUE TITLE
In a FEEL entry, variables change removes the focus

### ISSUE THREAD

**Issue by barmac** [bpmn-io/properties-panel#196]
__Describe the Bug__

When I update variables prop passed to a FEEL entry, it loses focus.

__Steps to Reproduce__

1. do this
2. do that
3. now this happens

__Expected Behavior__

Focus remains.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by barmac** [comment]
I created a test case to verify the future solution which needs to be implemented in bpmn-io/feel-editor: https://github.com/bpmn-io/properties-panel/commit/f7eb9eff5d7f49c4003a61bc7baf1771b06558bb

**Comment by marstamm** [comment]
I also noticed this during my FEEL prototyping. I worked around it by keeping the array reference and only changing the content, but I would not recommended this for production 😅 

The FEEL editor should expose a function to set new Variables

**Comment by barmac** [comment]
Fix for this requires https://github.com/bpmn-io/feel-editor/pull/33 to be merged and released.
