### ISSUE TITLE
Support tooltips for entries

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/properties-panel#202]
__Is your feature request related to a problem? Please describe__

The properties panel currently supports descriptions to provide more help and context to a specific entry.

Example: BPMN properties panel

<img width="268" alt="image" src="https://user-images.githubusercontent.com/9433996/205093293-a362568a-7b09-4002-8afb-704f41bd0e63.png">

Example: Forms properties panel

![image](https://user-images.githubusercontent.com/9433996/205093370-730ccd33-dcb6-4641-93c4-94064f51e8b7.png)

If you want to provide more context without cluttering the UI or using links to refer to external documentation, we'd need something else to display bigger chunks of explanations and help texts.

__Describe the solution you'd like__

Introduce the possibility of showing tooltips on specific entries, similar to descriptions, but only visible on hover.

![image](https://user-images.githubusercontent.com/9433996/205094127-81f63fc8-0e87-429f-b212-29d2c857bc2c.png)

__Describe alternatives you've considered__

Use native tooltips, which come with a lack of discoverability (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/725).

__Additional context__

Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/725
Related to https://github.com/bpmn-io/form-js/issues/305

**Comment by nikku** [comment]
If we go this route, let's clarify: Do we intend to incorporate a general "tooltip" facility (tooltips can be added anywhere) _or_ do we plan to create a certain UI pattern to solve "If you want to provide more context without cluttering the UI or using links to refer to external documentation...".

If the later is the case, what alternatives did we consider?

**Comment by nikku** [comment]
@pinussilvestrus Would be awesome if you could shed some light on what you want to achieve, and why, cf. https://github.com/bpmn-io/properties-panel/issues/202#issuecomment-1336277865.

**Comment by pinussilvestrus** [comment]
> If the later is the case, what alternatives did we consider

@romankostka @christian-konrad could you please give some insights on the research you already did on that one?

From my understanding the goal is to have some basic capability in the properties panel, as it turns out tooltips are a standard way to provide more context in forms land (detected in other form vendors)

**Comment by RomanKostka** [comment]
@pinussilvestrus that is correct!
Idea is to have some properties which need additional explanation via tooltips.

tooltips are a great way to provide additional explanation for unfamiliar properties. 
That will help our users to get along through our property panel.

But:
_Tooltips should not be used for information that is needed by the user for task completion!_
These information should always be visible in the UI.

regarding links:
Tooltips in general do not contain any interaction or links as they only appear on mouse- & keyboard-hover.
If we need to provide additional links to the users we should refer to the helper text.

Alternatives are 
1. provide additional information via text in the UI -> will lead to overloaded & cluttered interface.
2. provide additional information via documentation which is linked via helper texts -> not discoverable

**Comment by nikku** [comment]
Great. Then let's design generic tooltips feature in the core (this library), and easily re-usable across different places. :+1:

**Comment by christian-konrad** [comment]
> Tooltips can usually not be copied from. 

When you build them like this, yes. That's complete up to us.

**Comment by nikku** [comment]
@christian-konrad looking forward to build such an actually helpful version of tooltips. :slightly_smiling_face: 

Another good example: GitHub tooltips (recent additioin, I very much apprechicate these): 

![capture xiX9N5_optimized](https://user-images.githubusercontent.com/58601/206537126-ecaf1e89-36bd-45eb-8fe9-c2023c2a10e1.gif)

----

Moving this to backlog. Guess you'll pick this up from the HTO side of things as it fits into your agenda.

**Comment by nikku** [comment]
Another example where this would benefit connectors adoption:

Showing basic type information in a result mapping field (basics already possible via `abbr` tag): 

![capture Hf797e_optimized](https://user-images.githubusercontent.com/58601/208623617-f392c7c6-43c7-4a9a-9c9f-409008f20fe0.gif)

**Comment by nikku** [comment]
This was brought up again in a workshop last week and I created https://github.com/camunda/camunda-modeler/issues/3611 to track this topic including its purpose in the context of our modeling applications.

At this stage I'm convinced that this would yield value to our users and that we have discovered enough to move further if this is a priority.

**Comment by smbea** [comment]
Here is a demo of my [progress](https://github.com/bpmn-io/properties-panel/tree/202-support-tooltips) with supporting tooltips:

https://github.com/bpmn-io/properties-panel/assets/25825387/9cd43b29-200c-4fb2-802c-5dd542a07a75

**Comment by pinussilvestrus** [comment]
@smbea after our sync I just read over the `tooltip` role in ARIA: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tooltip_role

> The tooltip is displayed and disappears via **keyboard focus** and removal of focus and by the mouse events - mousing over and mousing out.

So in theory, the tooltips might also appear when the focus is on the label. I'm not sure whether we should do that, as the label focus is bound to an input and I never saw labels to have their own focus state.

Maybe we can introduce another way to toggle tooltips via keyboard, e.g. a keyboard shortcut when the focus is on the input? Together with `ESC` or focus out that could be a good compromise for keyboard users. `F1` is often times used for opening Help menus so that could be an option.

Let me know what you think 👍 cc @YanaSegal @christian-konrad

**Comment by nikku** [comment]
UX wise if something looks like a "tooltip element" I'd expect to be able to focus it using the keyboard (so the tooltip appears). Mouse interaction is a different thing (click => focus input it labels). 

`ESC` is the standard shortcut to close an open tooltip. `F1` is not really used as a focussed help shortcut and hence I'd not go that route if I could avoid it.

Cf. also [Carbon tooltip accessibility](https://carbondesignsystem.com/components/tooltip/accessibility/).

**Comment by nikku** [comment]
Could you share the different interaction patterns that we got in a screen capture? This way we're all on the same page.

What I tried quickly is to reproduce the interaction between a keyboard selectable label (that would open the tooltip) in the case of checkbox as well as input field labels:

![capture TL9CLX_optimized](https://github.com/bpmn-io/properties-panel/assets/58601/a7f7ff5e-9c7f-4fa4-9f71-d7b2f204c092)

_(Markup errors are due to the way I hacked this into an existing React app._)

For me this looks like a reasonable interaction:

* I can tab through the elements using the keyboard, and doing so would open the tooltip.
* I can click these elements, focusing and/or toggling the labeled input

**Comment by YanaSegal** [comment]
I agree with @nikku 
> I can tab through the elements using the keyboard, and doing so would open the tooltip

But I have a question: do we want to trigger it by clicking or hovering?
> I can click these elements, focusing and/or toggling the labeled input

**Comment by smbea** [comment]
I think the conversation is becoming confusing here. I'll schedule a quick sync to discuss this better
