### ISSUE TITLE
Improve validation support for `NumberFieldEntry`

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/properties-panel#206]
__Is your feature request related to a problem? Please describe__

Currently, dealing with number fields can be a little bit confusing. While there is browser built-in validation for number fields, how it is displayed is browser dependent and at least in Firefox requires a hover on top of the field, which is pretty hard to find.

![image](https://user-images.githubusercontent.com/17801113/212130923-531b25cb-f237-4c06-8f91-7a0cd650b099.png)

I don't think there exists a way to pipe the validation errors through to the UI via code (I could be wrong), though I know that via CSS we can at least apply some styling rules if the field is invalid, this might be useful. But in practice, I'd still rather have a similar validation experience as with the regular text fields. 

__Describe the solution you'd like__

Allow the supplying of a validation function for the `NumberFieldEntry` component, mirroring how it is done for `TextFieldEntry`.

__Describe alternatives you've considered__

Rely solely on browser default validation, unfortunately, the way browsers do this lacks a bit of clarity

__Additional context__

Initial comment that shows the confusion people experience with this: https://github.com/bpmn-io/form-js/pull/490#pullrequestreview-1245538661

@nikku @philippfromme I'm happy to implement this myself, if you think this is a positive addition.

**Comment by philippfromme** [comment]
I think we should ignore the browser validation as it's essentially useless. Would be great to have an attribute like [novalidate](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-novalidate) for number inputs.

We should
1. be able to add a validate function to a number field (similar to the text field https://github.com/bpmn-io/properties-panel/blob/main/src/components/entries/TextField.js#L99)
2. show validation errors below the number field
3. only commit if valid
