### ISSUE TITLE
When running in shadowDom, debounce causes evnet objects to reset target property.

### ISSUE THREAD

**Issue by siaikin** [bpmn-io/properties-panel#222]
### Describe the Bug

I use bpmn-js in shadowDom and [bpmn-js-properties-panel](https://kgithub.com/bpmn-io/bpmn-js-properties-panel). 
There is an error in the console when I try to modify properties in the property-panel.

![image](https://user-images.githubusercontent.com/24749324/219276327-06f09199-cbe2-4cec-b4fb-96f330db2b7c.png)
![image](https://user-images.githubusercontent.com/24749324/219276486-2fb745c2-b38a-4ff8-8c65-db769fc18e60.png)

After testing, I found that the reason was that setTmeout in debounce caused the event.target to be reset.
[event-target-changed-in-settimeout-in-shadow-dom](https://stackoverflow.com/questions/63607966/event-target-changed-in-settimeout-in-shadow-dom).

### Steps to Reproduce

https://codesandbox.io/s/distracted-leavitt-n8gxfn?file=/src/index.js

### Environment

- Host: Chrome 110.0.5481.100
- OS: Windows 10
- Library version: [e.g. 2.0.0]
  - bpmn-js-properties-panel: 1.17.2
  - @bpmn-io/properties-panel: 1.3.1

**Comment by nikku** [comment]
Interested in submitting a fix? Seems like we need to cache `event.target` for safe future use.

**Comment by siaikin** [comment]
> Interested in submitting a fix? Seems like we need to cache `event.target` for safe future use.

Same idea, I'll try.

**Comment by siaikin** [comment]
hi @nikku can you check this pr #224 ?

**Comment by nikku** [comment]
@siaikin Sorry for the delay. I hope I can have a look at this soon.

**Comment by nikku** [comment]
@siaikin Any reason you closed it? Is it no longer necessary?
