### ISSUE TITLE
Panels won't unfold with 1.5.0

### ISSUE THREAD

**Issue by steffen678** [bpmn-io/properties-panel#227]
### Describe the Bug

Panels don't unfold using version 1.5.0. Clicking on them does nothing. There's no error on the console.

### Steps to Reproduce

1. Setup any project using @bpmn-io/properties-panel 1.5.0.
2. Try clicking on the panels. 

### Expected Behavior

Panels should unfold. Going back to 1.4.0 fixed the issue. 

### Environment

- Host (Browser/Node version), if applicable: Firefox 111
- OS: Linux
- Library version: 1.5.0

**Comment by steffen678** [comment]
I'm using it inside a huge Angular 15 project. However, the modeler setup is not especially complex. I have the following libraries:

    "@bpmn-io/properties-panel": "1.5.0"
    "bpmn-js": "11.5.0",
    "bpmn-js-color-picker": "^0.5.0",
    "bpmn-js-properties-panel": "^1.19.1",
    "camunda-bpmn-moddle": "^7.0.1"

And here's a screencast:

[Screencast from 2023-03-16 11-09-16.webm](https://user-images.githubusercontent.com/1119538/225585366-45b4fbef-2326-41c8-8eed-02e58c536c70.webm)

Going back to 1.4.0 fixes the issue. I don't have time right now to provide a better example, sorry.

**Comment by barmac** [comment]
I can reproduce it in a codesandbox: https://codesandbox.io/s/trusting-archimedes-le2j7q?file=/src/index.js

My wild guess is that it's related to https://github.com/bpmn-io/properties-panel/pull/225

**Comment by barmac** [comment]
This is now fixed in [1.5.1](https://github.com/bpmn-io/properties-panel/blob/main/CHANGELOG.md#151)

**Comment by marstamm** [comment]
**Root Cause**

With #225 we now react to changes in `layoutConfig`. If none is supplied, the default `{}` will be added in the deconstruction. However, a new Object is created every render, so `useEffect` fires every render, causing infinite rendering loop.

We never tested for a config where `layoutConfig` is not set. I added a fix + additional tests to #228
