### ISSUE TITLE
How to disable FeelEntry, not allowing input

### ISSUE THREAD

**Issue by zxiaozhou** [bpmn-io/properties-panel#232]
### Is your feature request related to a problem? Please describe.
1. How to disable FeelEntry, not allowing input (because I want to show the default)
2. The default value is a feel expression, which is fixed.
3. In some scenarios, a default value needs to be set and cannot be changed. Normal input boxes display feel expressions incongruously
4. Just to show that this data is a feel expression
5. Currently, setting disabled to true is not valid

**Comment by barmac** [comment]
Is this about a missing feature or do you need support regarding the library usage? If it's the latter, please open a thread on the forum: https://forum.bpmn.io/

**Comment by zxiaozhou** [comment]
@barmac I think it's the same with the input box.So this is a missing feature

**Comment by barmac** [comment]
Then, please update the issue according to the feature request template as at the moment I can only guess what the missing feature is:

- Is your feature request related to a problem? Please describe.
- Describe the solution you'd like
- Describe alternatives you've considered
- Additional context

**Comment by barmac** [comment]
Closing this as invalid. Feel free to reopen the issue once you can give required info.
