### ISSUE TITLE
Allow local validation to be done on textAreas

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/properties-panel#233]
### Is your feature request related to a problem? Please describe.

For a properties panel extension (cf. https://github.com/bpmn-io/bpmn-js-json-data-provider/issues/1), I want to add a JSON TextArea with simple local validation.

Currently, the `validate` callback is only available for TextField, Number, Select and FEEL Fields.

### Describe the solution you'd like

Add the `validate` callback to TextAreas

### Describe alternatives you've considered

Create a lint-rule and have global validation

**Comment by nikku** [comment]
:+1: to provide the same facility to `TextArea`. At this point I'm wondering: Shall we get rid of some of our code duplication and extract it into a share behavior?
