### ISSUE TITLE
The open state is no longer handled by the library and the dmn properties panel needs to be handled at the same time, otherwise the style will be affected and the properties panel will not display

### ISSUE THREAD

**Issue by zxuanhong** [bpmn-io/properties-panel#247]
### Describe the Bug

The open state is no longer handled by the library and the dmn properties panel needs to be handled at the same time, otherwise the style will be affected and the properties panel will not display

### Steps to Reproduce

1. dmn properties panel is also introduced
2. Import style
3. dmn,bpmn properties panel is not displayed
4. dmn css
<img width="1104" alt="image" src="https://github.com/bpmn-io/properties-panel/assets/62740686/2cf2b636-e1f0-44ff-b8f4-0af8e4108d1c">

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS] 113
- OS: [e.g. Windows 7] mac
- Library version: [e.g. 2.0.0] 2.0.0

**Comment by barmac** [comment]
True, we need to migrate dmn-js-properties-panel too if one needs to share styles. Thanks for reporting.

**Comment by zxuanhong** [comment]
@barmac dmn has been fixed, I will close the current issue
