### ISSUE TITLE
old webpack loader can not loader es2020 grammer

### ISSUE THREAD

**Issue by lenvonsam** [bpmn-io/properties-panel#250]
env:
babel-core: 7.x
webpack: 4.x
bpmn-js-properties-panel: 2.0.0
bpmn-js: 13.2.0
@bpmn-io/properties-panel: 2.2.0

error:

<img width="845" alt="image" src="https://github.com/bpmn-io/properties-panel/assets/10168476/079b651a-4dc4-4cef-a9a4-f1015492e2d9">

``` js
this.parent? is es2020 grammer  can not be loader in old webpack
```
then, i add plugin —— @babel/plugin-proposal-optional-chaining for webpack loaders, but it is not work it.

how to resolve this problem?

**Comment by nikku** [comment]
@lenvonsam If you're using an old (ancient?) webpack loader, please either consult the internet as a source to find out how to consume modern javascript, upgrade your bundling infrastructure (webpack 4 is long outdate) or stick to a properties paneel version without modern language features.

Whatever option sounds best to you, go for it. We cannot unfortunately help you with your setup question. Maybe you reach out to other community members via [our forum](https://forum.bpmn.io/)?
