### ISSUE TITLE
Group tooltips are clipped when properties panel is scrollable (in firefox)

### ISSUE THREAD

**Issue by smbea** [bpmn-io/properties-panel#266]
### Describe the Bug

The `position:fixed` acts like `position:absolute` in Firefox for group headers when the properties panel container becomes scrollable.

https://github.com/bpmn-io/properties-panel/assets/25825387/0cd8558f-31a1-4a34-b52b-e9d7d9581c29

### Steps to Reproduce

1. open enough group header sections so that the properties panel becomes scrollable
2. toggle a group header tooltip
3. see that it appears hidden

### Expected Behavior

Should behave the same as in Chrome: tooltips should appear

### Environment

- Host (Browser/Node version), if applicable: Firefox
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by smbea** [comment]
This only happens in group headers because of the `position:sticky` they have

**Comment by Skaiir** [comment]
There seems to be some mentions of this in the [Firefox issues, ](https://bugzilla.mozilla.org/show_bug.cgi?id=1514291)seems they aren't planning on fixing it, so rendering it outside the group header is probably the only choice 👍

**Comment by smbea** [comment]
I have tried that in https://github.com/bpmn-io/properties-panel/pull/268 and it works. The only issue is that is messes up the focus tree

**Comment by smbea** [comment]
After some discussion, we decided to fix the display issues right now and I will open a separate issue to address the focus since it may be that we need to programatically control it.
