### ISSUE TITLE
Pop container can easily cause the entire page to overflow.Can you add fill to currentcolor for the icon to facilitate color setting

### ISSUE THREAD

**Issue by zxuanhong** [bpmn-io/properties-panel#277]
### Describe the Bug

1. The bullet frame should not be mounted under the root body.This can cause penetration out of the container, resulting in a page overflow
2. The top left icon color should be modifiable to fit the dark mode

<img width="1687" alt="image" src="https://github.com/bpmn-io/properties-panel/assets/62740686/29491b52-f9a5-4424-b4fa-5415b64b1dc4">

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS] chrome 110
- OS: [e.g. Windows 7] mac
- Library version: [e.g. 2.0.0]  3.3.2

**Comment by nikku** [comment]
CC @pinussilvestrus. Maybe you can have a look?

**Comment by zxuanhong** [comment]
And how do I disable this pop-up

**Comment by christian-konrad** [comment]
@zxuanhong you can easily change colors of the drag icon with css filters

**Comment by zxuanhong** [comment]
@christian-konrad I think it's easier to set up with currentColor

**Comment by pinussilvestrus** [comment]
> The bullet frame should not be mounted under the root body.This can cause penetration out of the container, resulting in a page overflow

With https://github.com/bpmn-io/properties-panel/pull/280 we aim to add an option to configure the parent container of the popup editor.

**Comment by zxuanhong** [comment]
@pinussilvestrus I only used bpmn js, so  need to adjust the bpmn-js-properties-panel component configuration

**Comment by pinussilvestrus** [comment]
@zxuanhong this option will be present via https://github.com/bpmn-io/bpmn-js-properties-panel/pull/970 in bpmn-js-properties-panel as well

**Comment by zxuanhong** [comment]
@pinussilvestrus Thank you very much. I think there should be no problem only to set up, so I will close the current issue
