### ISSUE TITLE
Popup editor is bubbling keyboard events to the parent

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/properties-panel#281]
### Describe the Bug

When focus is inside a popup, it does not prevent bubbling keyboard events to it's parent. E.g., in the scope of the Camunda Desktop Modeler, `A` is triggering the append menu:

https://github.com/bpmn-io/properties-panel/assets/9433996/ef35a037-9038-445b-a683-f94a861020dc

Also, in the Form Playground Demo, it is triggering switching modes via CTRL+SHIFT+P

![Kapture 2023-09-08 at 09 30 42](https://github.com/bpmn-io/properties-panel/assets/9433996/e7df14da-0aaa-4c01-a61f-b127b060a8d2)

### Steps to Reproduce

1. Open a BPMN or Forms file
2. Open a FEEL Popup editor
3. Execute a keyboard shortcut, e.g. `A` 
4. See the event is bubbling up to the parent

### Expected Behavior

Events should never bubble up to the parent when the focus is inside a popup.

### Environment

- Host (Browser/Node version), if applicable: Chrome 116
- OS: macOS 13.4.1
- Library version: 3.4.0

**Comment by pinussilvestrus** [comment]
Learning: never trust too much [on an external library](https://github.com/focus-trap/focus-trap) that handles stuff you would expect. 🐒

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/properties-panel/pull/282.
