### ISSUE TITLE
For the FEEL popup editor, provide more detailed focused state

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/properties-panel#290]
### Why should we do it?

In the Desktop Modeler, we have global keyboard shortcuts that trigger independent of the handling in the DOM tree. For a good editing experience, these have to be disabled when focusing on a text editor.

### What should we do?

Provide `focusIn` and `focusOut` events.

alternative: have the focusIn and focusOut events added from the integrating editor, [like we do for properties panel focus events](https://github.com/camunda/camunda-modeler/blob/29f0379b770dea28dfe5dba3166322d133656a8e/client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/PropertiesPanelKeyboardBindings.js). For this, it would be helpful if the `.opened` event contains the DOM element of the popup so additional event listeners can be attached.

related to https://github.com/camunda/camunda-modeler/issues/3877#issuecomment-1733199580

**Comment by nikku** [comment]
I'm in favor of doing this, cf. https://github.com/bpmn-io/properties-panel/pull/294#issuecomment-1733778560.

**Comment by marstamm** [comment]
Closed with #294
