### ISSUE TITLE
Undo/redo is broken in FEEL popup

### ISSUE THREAD

**Issue by barmac** [bpmn-io/properties-panel#295]
### Describe the Bug

Undo/redo is broken in FEEL popup.

### Steps to Reproduce

Given I type in the FEEL entry, when I press cmd+Z and cmd+Y, in FEEL popup, the cursor changes position but doesn't change the state on undo, and adds characters via redo.

### Expected Behavior

* [ ] Undo cancels the most recent command.
* [ ] Redo repeats the cancelled command.

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: v5.5.0

**Comment by barmac** [comment]
I am postponing the fix for this until we clarify https://github.com/camunda/camunda-modeler/issues/3902

**Comment by nikku** [comment]
Closing this issue in favor of https://github.com/camunda/camunda-modeler/issues/3902. 

We'll implement a working thing, some day, maybe.
