### ISSUE TITLE
Consider adding type="button" to <button> elements

### ISSUE THREAD

**Issue by jonathanbp** [bpmn-io/properties-panel#299]
### Is your feature request related to a problem? Please describe.

I had a long fight with a properties panel where clicking e.g. the buttons to expand a group (in a header) would cause the browser to navigate. I finally tracked it down to a `<form>` ancestor getting submitted whenever by the `<button>` clicks.

### Describe the solution you'd like

The default action for `<button>`s without a `type` attribute is to submit the closest ancestor form. I don't think that was the intention with any of your buttons. If you add a `type="button"` attribute to your buttons you won't get this behaviour. See e.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button.

### Describe alternatives you've considered

I added a `onsubmit="return false"` attribute to my form which solved the issue for me (since it is never supposed to be submitted anyway).

**Comment by nikku** [comment]
@jonathanbp Thanks a lot. I agree with your rationale. 

If you want to contribute this feature, we'd be happy to accept it. Moving into our `spring cleaning` category for the moment.

**Comment by pinussilvestrus** [comment]
@jonathanbp Mind you sharing your scenario in which the properties panel was embedded into a `form` element? Was it per accident, or is there a reason for it?

Good catch anyways 👍

**Comment by jonathanbp** [comment]
I'm embedding a bpmn instance into an existing system which had the `form` as part of it's structure. The place where it is embedded normally contains misc input elements and the `form`s job is primarily styling - by way of https://fomantic-ui.com/collections/form.html.
