### ISSUE TITLE
Add missing translation capabilities to ListGroup

### ISSUE THREAD

**Issue by ulli-hoeness** [bpmn-io/properties-panel#358]
### Is your feature request related to a problem? Please describe.

ListGroup has a create, delete and toggle button which all lack translations. Tooltips for these buttons as well as the indicator for how many items the listGroup contains, also lack translations. 

### Describe the solution you'd like

It should be possible to create translations for these buttons and their tooltips. We could achieve this by passing the translate function as a prop.

### Additional context

![grafik](https://github.com/bpmn-io/properties-panel/assets/165301639/2ee21dbe-5546-4a68-ae0f-e806e4680fa6)

![grafik](https://github.com/bpmn-io/properties-panel/assets/165301639/7cc3325b-702f-435b-ad81-3e02adc55207)

![grafik](https://github.com/bpmn-io/properties-panel/assets/165301639/dd4d5509-f499-4f31-9586-8f1ffd265720)

![grafik](https://github.com/bpmn-io/properties-panel/assets/165301639/cb861fc2-6fd6-4544-9220-b9fcd533728f)

**Comment by ulli-hoeness** [comment]
I would like to tackle this issue.

**Comment by barmac** [comment]
I think it makes sense. Feel free to tag me on the PR.
