### ISSUE TITLE
Close button of popup editor overlaps text during editing

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/properties-panel#364]
### Describe the Bug

Currently, the close button is overlapping some of the feel text when editing. This causes 

![grafik](https://github.com/bpmn-io/properties-panel/assets/17801113/da248df7-bf33-440e-abc8-8bb08e011c07)

### Steps to Reproduce

1. Pop a feel expression out
2. Enter a bunch of text into it
3. See above picture

### Expected Behavior

3. There should not be a conflict between this button and the text display. Move the Close button to the top bar of the FEEL Popup Editor. The area below will be reserved only for editing and previewing FEEL expressions.

**Comment by volodymyr-melnykc** [comment]
To solve this issue and improve overall visual alignment, move the Close button to the top bar of the FEEL Popup Editor. This will reserve the area below only for editing and previewing FEEL expressions.
The button to close the popup should be an icon button, and hovering it should show the tooltip "Close."

![FEEL Popup Editor](https://github.com/bpmn-io/properties-panel/assets/143816833/d4a91375-b6c9-450c-96ad-cc4c7749a448)

**Comment by Skaiir** [comment]
Should we consider using a dock icon instead? It might better convey the idea that the change is not destructive, what do you think?

**Comment by volodymyr-melnykc** [comment]
Agreed that a tooltip for the close button will indicate that changes are saved when closing, so this action is not destructive.
