### ISSUE TITLE
localError should take precedence over globalError

### ISSUE THREAD

**Issue by rcnicky** [bpmn-io/properties-panel#370]
### Describe the Bug

localError should take precedence over globalError, I use the custom translate module can not change the i18n language

![image](https://github.com/bpmn-io/properties-panel/assets/142192623/9dc29f04-c780-4cac-a9fc-188ec6405be0)

![image](https://github.com/bpmn-io/bpmn-js-element-templates/assets/142192623/7ca4beac-9716-48dd-a294-980fb43fdd6e)

![image](https://github.com/bpmn-io/bpmn-js-element-templates/assets/142192623/9afca95c-18c7-439d-99b0-b5e68ab87a22)

 

### Expected Behavior

localError should take precedence over globalError, should show chinese error label

https://github.com/bpmn-io/properties-panel/blob/c34fba48f145714a5f5729b60a22ed26aa6dbe3e/src/components/entries/TextField.js#L138

### Environment

- Host (Browser/Node version): Edge 18, Chrome 69
- OS: Windows11
- Library version: 3.21.0

**Comment by barmac** [comment]
Hi,

From the issue, I don't understand why we should implement your suggestion. The global error (better called "external error") precedence is required to support errors provided in https://github.com/camunda/linting/. In that case, we find it more relevant for the user that some property is not supported at all than that the value of the unsupported property would not have been valid if it had been supported.

If there's some problem in the translation labels that prevents i18n, please share it in another issue.
