### ISSUE TITLE
SelectEntry component support multiple

### ISSUE THREAD

**Issue by ruanzy** [bpmn-io/properties-panel#384]
SelectEntry component support multiple

I am trying to extend the candidate component to SelectEntry it is success.

but I want to expand the CandidateUser component to select multiple   How should I do it

<img width="241" alt="lQLPJxeJQAv8odfNAVbNAeGwKWgIab4UeVgG27shNKDqAA_481_342" src="https://github.com/user-attachments/assets/b63b49f3-41ce-42e6-94b4-2e30c714b87e">

**Comment by barmac** [comment]
For the questions on the libraries usage, please head to https://forum.bpmn.io
Don't forget to share your code!
