### ISSUE TITLE
Prepare libraries to be published + integrated in downstream projects

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/properties-panel#5]
> **This is an epic issue that may be broken down into multiple tasks if needed**

__What should we do?__

We use this project as a starting point for developing the next properties panel features. Once we reached a certain point this quarter, we should decide how we want to publish this. That includes
* [x] Split up the project into two individual ones (names to be discussed)
  * `bpmn-io/properties-panel`, includes core components (cf. #77) 
  * `bpmn-io/bpmn-properties-panel`, includes bpmn implementation + providers (will become `bpmn-js-properties-panel@1.0.0` in the future eventually) (cf. https://github.com/bpmn-io/bpmn-properties-panel/pull/1)
* [x] Prepare distribution infrastructure
* [x] Release first version(s) 
* [x] https://github.com/camunda/camunda-modeler/issues/2347
  * [x] <del>`camunda-bpmn-js`</del> => Not for now
  * [x] Camunda Modeler
* [x] Add minimal API docs for bpmn properties panel
  * cf. [form-js API docs](https://github.com/bpmn-io/form-js/tree/master/packages/form-js-editor#api)
* [x] Add minimal working examples => https://github.com/bpmn-io/bpmn-js-examples/tree/properties-panel-next-example
  * follow up once we have the Camunda Platform properties available: https://github.com/bpmn-io/bpmn-js-examples/issues/135 

Several child issues will be created in the different projects once the split-up is done. Also, cf. to the [Kickoff results](https://github.com/bpmn-io/properties-panel-next/issues/5#issuecomment-871380592).

__Why should we do it?__

Be ready to release the stuff.

**Comment by pinussilvestrus** [comment]
First sketch for a new example: https://github.com/bpmn-io/bpmn-js-examples/tree/properties-panel-next-example/properties-panel-next-extension

**Comment by pinussilvestrus** [comment]
**Summary of Kickoff (30th June 2021)**

Participants: Maciej, Max, Philipp, Volker, Niklas

Miro Board: https://miro.com/app/board/o9J_l9YSCco=/

_Decisions (summary)_
* Niklas is the DRI for it
* We will not add any more features until the first release, goal is to have it out of the door
* We will have two projects, one for the core, one for the bpmn properties panel (names to be decided)
* We will include the properties providers in the bpmn properties panel package
* We will use `@bpmn-io/bpmn-properties-panel` (or something similar) as a private dependency until Platform Properties are not ready
  * As GitHub dependency or private npm package
* We aim to release the complete Panel as bpmn-js-properties-panel@1.0.0 once we are done
* We aim to integrate the Cloud Properties Panel into the Camunda Modeler sooner than later (goal: August release)
* We aim minimal API docs for the bpmn properties panel + examples

_Action items_
* Get #27 done (@pinussilvestrus) 
* Update epic issue for several working items (@pinussilvestrus)

**Comment by pinussilvestrus** [comment]
Work is happening on these branches
* core: https://github.com/bpmn-io/properties-panel-next/tree/5-prepare-project-split
* bpmn implementation: https://github.com/bpmn-io/bpmn-properties-panel/tree/5-split-up-projects
* example: https://github.com/bpmn-io/bpmn-js-examples/tree/properties-panel-next-example

**Comment by pinussilvestrus** [comment]
**How to release stuff**. 

_Proposal: We keep it simple for now_

* release `@bpmn-io/properties-panel@0.1.0`, integrate it into `bpmn-io/bpmn-properties-panel`
* release `@bpmn-io/bpmn-properties-panel@0.1.0`, integrate it into Camunda Modeler (Cloud Editor) only, skip `camunda-bpmn-js` for now

Reason: If we would release `bpmn-js-properties-panel@1.0.0-alpha.x` and integrate it into `camunda-bpmn-js`, we would have to live with this alpha stage across the chain for a while. It would be harder to release bug fixes in camunda-bpmn-js for the time being.

I'd simply use this "intermediate" dependency while we're not ready for v1.0.0. If we have everything ready, we can simply release `bpmn-js-properties-panel@1.0.0` and remove the old properties panel completely.

**Comment by pinussilvestrus** [comment]
A way of temporarily disable the "old" properties panel is [shown in the User Test artifact](https://github.com/camunda/camunda-modeler/commit/56e396fb016a807e842a62adf931c81745ce1f00#diff-27f1e75972749cdee1c792f308ecbbc3ccb3ad55b52fc4dc7fc3756a7d180e70R84-R87).

```js
// exclude old properties panel + provider coming from camunda-bpmn-js
function excludeOldModules(modules) {
  return modules.filter(m => !has(m, 'propertiesPanel') && !has(m, 'propertiesProvider'));
}
```

We could even consider doing this via feature toggle if we want to.

**Comment by nikku** [comment]
> _We keep it simple for now._

Agreed. :smile: 

If we want to [feature toggle this](https://github.com/bpmn-io/properties-panel/issues/5#issuecomment-873902148) releasing as another library is mandatory.

**Comment by pinussilvestrus** [comment]
Even simpler: simply integrate it via GitHub tag in this intermediate state

```js
"@bpmn-io/bpmn-properties-panel": "github:bpmn-io/bpmn-properties-panel#v0.1.0"
```
