### ISSUE TITLE
First list item behavior kicks in place when switching element

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/properties-panel#63]
__Describe the Bug__

We have a behavior to open + focus on the first element when adding list items. However, this behavior also kicks in place when switching between elements. This only occurs, when the List Group is visible on both elements.

![Kapture 2021-06-09 at 10 06 34](https://user-images.githubusercontent.com/9433996/121317273-6f5aa700-c90a-11eb-8344-954d02da93ed.gif)

__Steps to Reproduce__

1. Create a new output on a start event => auto focus behavior is working correctly
2. Close Output group
3. Switch to service task
4. Swtich back to start event
5. See the auto focus behavior kicks in place => first item is focused

__Expected Behavior__

Output group remains closed.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 91
- OS: macOS 10.15.7
- Library version: current `main`

**Comment by MaxTru** [comment]
This also affects the items within a list. See for example process variables:
![persistedToggleState](https://user-images.githubusercontent.com/42800119/126327022-5d043746-179b-4e00-a638-36dfb6a3c0a3.gif)

**Comment by pinussilvestrus** [comment]
> This also affects the items within a list. See for example process variables:
> ![persistedToggleState](https://user-images.githubusercontent.com/42800119/126327022-5d043746-179b-4e00-a638-36dfb6a3c0a3.gif)

I think that's a different issue. The issue description is actively opening an item due to the autoFocus behavior. 

The second issue is probably a problem with the list-item components: the second item keeps its collapsed state, no matter for which element. Probably due to missing or non-unique `key` values for the child components.

**Comment by MaxTru** [comment]
> > This also affects the items within a list. See for example process variables:
> > ![persistedToggleState](https://user-images.githubusercontent.com/42800119/126327022-5d043746-179b-4e00-a638-36dfb6a3c0a3.gif)
> 
> I think that's a different issue. The issue description is actively opening an item due to the autoFocus behavior.
> 
> The second issue is probably a problem with the list-item components: the second item keeps its collapsed state, no matter for which element. Probably due to missing or non-unique `key` values for the child components.

Will open a new issue then.
