### ISSUE TITLE
Enable multi-select (and empty) state for the properties panel

### ISSUE THREAD

**Issue by andreasgeier** [bpmn-io/properties-panel#69]
__What should we do?__

We need to consider the multi-select scenario for the properties panel. Currently, the panel only works correctly if one element is select at a time.

(Optional in the Zeebe scope:) We should also consider the no-selection / empty state. This is not possible in the BPMN and DMN world but we have an empty state in Forms.

Cf. the [visual IDE prototype](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v17/) (Select "empty state" and "multi state" elements) 

![image](https://user-images.githubusercontent.com/9433996/169284069-586643e1-8cb4-4ea7-b33c-d57bfa1b7fae.png)

![image](https://user-images.githubusercontent.com/9433996/169258857-4f675e95-e3d7-4d2f-995a-54c162b0eb7f.png)

For both cases: background color is `--color-grey-225-10-95`

__Why should we do it?__

There is no current solution. In a multi-select scenario, the panel shows just one of the select elements. It is even possible to edit this (random?) element in the panel.

Related to https://github.com/camunda/camunda-modeler-design/issues/100

**Comment by pinussilvestrus** [comment]
There is already an ["empty" state in the core](https://github.com/bpmn-io/properties-panel-next/blob/main/src/properties-panel/PropertiesPanel.js#L102-L104), although it might not be reachable in the Zeebe Properties Panel. We can definitely improve it, though.

**Comment by pinussilvestrus** [comment]
Cf. to the prototype about multi-select & empty state: https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v14/

Let's move it to the backlog until we don't know whether we tackle this one in particular in the Q3 design finishing efforts.

**Comment by pinussilvestrus** [comment]
/cc @andreasgeier @christian-konrad @MaxTru 

What I'm wondering: are we okay with using these images for multi and empty state? They are really BPMN specific

![image](https://user-images.githubusercontent.com/9433996/169258599-fc9034de-f950-4ad5-bbc5-414740b35fd3.png)

![image](https://user-images.githubusercontent.com/9433996/169258232-699547f5-658e-4062-b1b6-65bac9125617.png)

I'd assume that these **could be overridden** by the implementor once they support multi select (dmn-js, form-js). Empty state wouldn't be a thing anyway.

**Comment by pinussilvestrus** [comment]
I'd propose to go in the same direction [as for the Header](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/render/PanelHeaderProvider.js). Have a provider that defines the contents of the placeholders on implementor level.

```js
const PanelPlaceholderProvider = {
  getEmptyText: (element) => {
    return 'Select an element to edit its properties.';
  },
  getMultipleText: (element) => {
    return 'Multiple elements are selected. Use the context pad for actions.';
  },
  getEmptyIcon: () => {},
  getMultipleIcon: () => {}
};
```

**Comment by pinussilvestrus** [comment]
Just in theory (as we anyway don't support it by now): I think we would need different images for DMN and Forms - or simply display it as text-only. /cc @andreasgeier 

**DMN**

![image](https://user-images.githubusercontent.com/9433996/169300910-c58717c6-2dab-4f92-a887-5faf82ab89c1.png)

![image](https://user-images.githubusercontent.com/9433996/169301185-e3c70c5c-12bc-4ede-b1a3-5a455a48e0b1.png)


**Form**

![image](https://user-images.githubusercontent.com/9433996/169301016-56127668-91ad-44e1-a71c-9d0712e82f70.png)

![image](https://user-images.githubusercontent.com/9433996/169301351-eeab55a3-3264-41bd-9419-8fb6827107a9.png)
