### ISSUE TITLE
Publish transpiled content

### ISSUE THREAD

**Issue by barmac** [bpmn-io/properties-panel#80]
__Is your feature request related to a problem? Please describe__

The library cannot be used without babel transpilation step. This leads to quirks in configuration like https://github.com/bpmn-io/bpmn-properties-panel/pull/1/files#diff-8e222682e48a1d2eea1bcdc904e33649668fc90a147b39ff5be60cef8371e6b4R55-R64

__Describe the solution you'd like__

Publish transpiled code (cf. we do with [dmn-js](https://github.com/bpmn-io/dmn-js/blob/develop/packages/dmn-js-decision-table/package.json#L11))

__Describe alternatives you've considered__

None.

__Additional context__

**Comment by nikku** [comment]
We should investigate if we can deliver this with our initial release.

**Comment by nikku** [comment]
It otherwise gets impossible to consume it in a sane manner.

**Comment by pinussilvestrus** [comment]
Good Catch!
